/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.treinamento.locadora.view;

import br.com.treinamento.locadora.controller.MenuController;

/**
 *
 * @author joaop
 */
public class MenuView extends javax.swing.JFrame {

    MenuController menuController = new MenuController(MenuView.this);

    public MenuView() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCliente = new javax.swing.JButton();
        btFilme = new javax.swing.JButton();
        btVendedor = new javax.swing.JButton();
        btLocacao = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btDevolucao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCliente = new javax.swing.JMenuItem();
        miVendedor = new javax.swing.JMenuItem();
        miFilme = new javax.swing.JMenuItem();
        miLocacao = new javax.swing.JMenuItem();
        miDevolucao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Locadora");

        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/treinamento/locadora/img/clientes.png"))); // NOI18N
        btCliente.setText("Cliente");
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        btFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/treinamento/locadora/img/filme.png"))); // NOI18N
        btFilme.setText("Filmes");
        btFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFilmeActionPerformed(evt);
            }
        });

        btVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/treinamento/locadora/img/funcionario.png"))); // NOI18N
        btVendedor.setText("Vendedor");
        btVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendedorActionPerformed(evt);
            }
        });

        btLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/treinamento/locadora/img/locação.png"))); // NOI18N
        btLocacao.setText("Locação");
        btLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocacaoActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/treinamento/locadora/img/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setMaximumSize(new java.awt.Dimension(117, 39));
        btSair.setMinimumSize(new java.awt.Dimension(117, 39));
        btSair.setPreferredSize(new java.awt.Dimension(117, 39));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btDevolucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/treinamento/locadora/img/devolucao.png"))); // NOI18N
        btDevolucao.setText("Devolução");
        btDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolucaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btVendedor)
                .addGap(10, 10, 10)
                .addComponent(btFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLocacao)
                .addGap(10, 10, 10)
                .addComponent(btDevolucao)
                .addGap(10, 10, 10)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btCliente)
                        .addComponent(btVendedor)
                        .addComponent(btFilme)
                        .addComponent(btLocacao)
                        .addComponent(btDevolucao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastro ");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        miCliente.setText("Cliente");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miCliente);

        miVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        miVendedor.setText("Vendedor");
        miVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(miVendedor);

        miFilme.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        miFilme.setText("Filmes");
        miFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFilmeActionPerformed(evt);
            }
        });
        jMenu1.add(miFilme);

        miLocacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        miLocacao.setText("Locação");
        miLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLocacaoActionPerformed(evt);
            }
        });
        jMenu1.add(miLocacao);

        miDevolucao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        miDevolucao.setText("Devolução");
        miDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDevolucaoActionPerformed(evt);
            }
        });
        jMenu1.add(miDevolucao);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sistema");

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu2.add(miLogout);

        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        jMenu2.add(miSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendedorActionPerformed
        this.menuController.acaoBotaoVendedor();
    }//GEN-LAST:event_btVendedorActionPerformed

    private void btLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocacaoActionPerformed
        this.menuController.acaoBotaoLocacao();
    }//GEN-LAST:event_btLocacaoActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        this.menuController.acaoBotaoCliente();
    }//GEN-LAST:event_btClienteActionPerformed

    private void btFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFilmeActionPerformed
        this.menuController.acaoBotaoFilme();
    }//GEN-LAST:event_btFilmeActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.menuController.acaoBotaoSair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolucaoActionPerformed
        this.menuController.acaoBotaoDevolucao();
    }//GEN-LAST:event_btDevolucaoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
        this.menuController.acaoCadastroCliente();
    }//GEN-LAST:event_miClienteActionPerformed

    private void miVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVendedorActionPerformed
         this.menuController.acaoCadastroVendedor();
    }//GEN-LAST:event_miVendedorActionPerformed

    private void miFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFilmeActionPerformed
         this.menuController.acaoCadastroFilme();
    }//GEN-LAST:event_miFilmeActionPerformed

    private void miLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLocacaoActionPerformed
        this.menuController.acaoCadastroLocacao();
    }//GEN-LAST:event_miLocacaoActionPerformed

    private void miDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDevolucaoActionPerformed
        this.menuController.acaoCadastroDevolucao();
    }//GEN-LAST:event_miDevolucaoActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
         this.menuController.acaoSistemaLogout();
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
         this.menuController.acaoSistemaSair();
    }//GEN-LAST:event_miSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btDevolucao;
    private javax.swing.JButton btFilme;
    private javax.swing.JButton btLocacao;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVendedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miDevolucao;
    private javax.swing.JMenuItem miFilme;
    private javax.swing.JMenuItem miLocacao;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miVendedor;
    // End of variables declaration//GEN-END:variables
}
